language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - ~/.cache
script:
  - npm run lint
  - npm test
  - npm run start:test -- --silent &
  - $(npm bin)/cypress run -- --record --parallel
on:
  branch: [master, development]
