name: build and push

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etcaterva/echaloasuerte:${BRANCH_NAME}
          build-args: |
            arg1=value1
            arg2=value2

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
