name: build and push

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch


      - name: Set app_env var
        id: setvars
        run: |
          if [[ "${{github.ref}}" == "refs/heads/prod" ]]; then
              echo "APP_ENV=production" >> $GITHUB_ENV
          else
              echo "APP_ENV=staging" >> $GITHUB_ENV
          fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etcaterva/echaloasuerte:${{ steps.extract_branch.outputs.branch }}
          build-args: |
            commit_sha=${GITHUB_SHA}
            app_env=$APP_ENV

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
